import type { Plugin, ResolvedConfig } from "vite";
import { posix } from "node:path";

const SW_URL = "sw.js";

/**
 * Minimal PWA plugin: emits a precaching service worker + copies the
 * webmanifest at build time.
 *
 * Runtime strategy:
 *  - Navigations: network-first, fall back to the precached shell offline.
 *  - Precached assets: stale-while-revalidate.
 *  - Non-GET and cross-origin requests (Drive REST, /api on prod is
 *    same-origin but keep it safe) pass through untouched.
 *
 * Hand-rolled instead of vite-plugin-pwa: fewer moving parts, no workbox
 * peer-dependency risk on Vite 8.
 */
export function pwaPlugin(): Plugin {
  let config: ResolvedConfig | null = null;

  return {
    name: "charasheet-pwa",
    apply: "build",
    enforce: "post",

    configResolved(resolved) {
      config = resolved;
    },

    async generateBundle(_options, bundle) {
      if (!config) return;
      const base = config.base || "/";

      const urls = new Set<string>();
      for (const fileName of Object.keys(bundle)) {
        if (fileName.endsWith(".map")) continue;
        // Every emitted asset (chunk, css, images, manifest, icons) is
        // either content-hashed or effectively immutable → precache.
        if (fileName.endsWith(".html") || fileName.startsWith("assets/") || fileName === "manifest.webmanifest" || /\.(png|ico|svg|webmanifest)$/.test(fileName)) {
          urls.add(posix.join(base, fileName));
        }
      }

      // The SW itself is generated with a build-time version stamp; index.html
      // is precached under its URL directly.
      urls.add(posix.join(base, "index.html"));

      const files = [...urls].sort();
      this.emitFile({
        type: "asset",
        fileName: SW_URL,
        source: renderSw(files, base),
      });
    },
  };
}

function renderSw(urls: string[], base: string): string {
  const scope = base.endsWith("/") ? base : base + "/";
  return `// Generated by scripts/pwa-plugin.ts at build time — do not edit.
const VERSION = ${JSON.stringify(new Date().toISOString())};
const SCOPE = ${JSON.stringify(scope)};
const PRECACHE = "precache-" + VERSION;
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(PRECACHE);
      // cache: "reload" bypasses the HTTP cache so precache never poisons itself.
      await Promise.allSettled(
        PRECACHE_URLS.map((url) => cache.add(new Request(url, { cache: "reload" }))),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key !== PRECACHE) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req).catch(() =>
        caches.match(${JSON.stringify(scope + "index.html")}).then(
          (shell) => shell ?? Response.error(),
        ),
      ),
    );
    return;
  }

  // Same-origin static asset: serve from cache when we have it (SWR —
  // refresh in the background), otherwise fetch.
  event.respondWith(
    (async () => {
      const cached = await caches.match(req);
      const network = fetch(req)
        .then((response) => {
          if (response && response.status === 200) {
            // Clone first: cache.put consumes the body, and the original
            // still has to be returned to the page.
            caches.open(PRECACHE).then((cache) => cache.put(req, response.clone()));
          }
          return response;
        })
        .catch(() => undefined);
      return cached || (await network) || fetch(req);
    })(),
  );
});
`;
}